# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='mark',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('superlike', 'superlike')], max_length=20, verbose_name='滑动类型'),
        ),
    ]
