# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='female', max_length=8, verbose_name='匹配的性别'),
        ),
    ]
